package entidades;
// Generated 11/10/2017 03:41:20 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ConfirmarEvento generated by hbm2java
 */
@Entity
@Table(name = "confirmar_evento", catalog = "egresoft")
public class ConfirmarEvento implements java.io.Serializable {

	private Integer idConfirmarEvento;
	private int idEvento;
	private long idEgresado;

	public ConfirmarEvento() {
	}

	public ConfirmarEvento(int idEvento, long idEgresado) {
		this.idEvento = idEvento;
		this.idEgresado = idEgresado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idConfirmar_evento", unique = true, nullable = false)
	public Integer getIdConfirmarEvento() {
		return this.idConfirmarEvento;
	}

	public void setIdConfirmarEvento(Integer idConfirmarEvento) {
		this.idConfirmarEvento = idConfirmarEvento;
	}

	@Column(name = "idEvento", nullable = false)
	public int getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(int idEvento) {
		this.idEvento = idEvento;
	}

	@Column(name = "idEgresado", nullable = false)
	public long getIdEgresado() {
		return this.idEgresado;
	}

	public void setIdEgresado(long idEgresado) {
		this.idEgresado = idEgresado;
	}

}
