package entidades;
// Generated 16/11/2017 09:52:27 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Convenio generated by hbm2java
 */
@Entity
@Table(name = "convenio", catalog = "egresoft")
public class Convenio implements java.io.Serializable {

	private Integer idConvenio;
	private String nombrelCovenio;
	private String infoConvenio;
	private String personaContacto;
	private String imagenConvenio;

	public Convenio() {
	}

	public Convenio(String nombrelCovenio, String infoConvenio, String personaContacto, String imagenConvenio) {
		this.nombrelCovenio = nombrelCovenio;
		this.infoConvenio = infoConvenio;
		this.personaContacto = personaContacto;
		this.imagenConvenio = imagenConvenio;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idConvenio", unique = true, nullable = false)
	public Integer getIdConvenio() {
		return this.idConvenio;
	}

	public void setIdConvenio(Integer idConvenio) {
		this.idConvenio = idConvenio;
	}

	@Column(name = "nombrel_covenio", nullable = false, length = 45)
	public String getNombrelCovenio() {
		return this.nombrelCovenio;
	}

	public void setNombrelCovenio(String nombrelCovenio) {
		this.nombrelCovenio = nombrelCovenio;
	}

	@Column(name = "info_convenio", nullable = false, length = 45)
	public String getInfoConvenio() {
		return this.infoConvenio;
	}

	public void setInfoConvenio(String infoConvenio) {
		this.infoConvenio = infoConvenio;
	}

	@Column(name = "persona_contacto", nullable = false, length = 45)
	public String getPersonaContacto() {
		return this.personaContacto;
	}

	public void setPersonaContacto(String personaContacto) {
		this.personaContacto = personaContacto;
	}

	@Column(name = "imagen_convenio", nullable = false, length = 45)
	public String getImagenConvenio() {
		return this.imagenConvenio;
	}

	public void setImagenConvenio(String imagenConvenio) {
		this.imagenConvenio = imagenConvenio;
	}

}
