package entidades;
// Generated 13/10/2017 09:42:26 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Evento generated by hbm2java
 */
@Entity
@Table(name = "evento", catalog = "egresoft")
public class Evento implements java.io.Serializable {

	private Integer idEvento;
	private String nombreEvento;
	private String url_redireccion;
	private String imagenEvento;
	private String descripcionEvento;

	public Evento() {
	}

	public Evento(String nombreEvento, String url_redireccion, String imagenEvento,
			String descripcionEvento) {
		this.nombreEvento = nombreEvento;
		this.url_redireccion = url_redireccion;
		this.imagenEvento = imagenEvento;
		this.descripcionEvento = descripcionEvento;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idEvento", unique = true, nullable = false)
	public Integer getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(Integer idEvento) {
		this.idEvento = idEvento;
	}

	@Column(name = "nombre_evento", nullable = false, length = 45)
	public String getNombreEvento() {
		return this.nombreEvento;
	}

	public void setNombreEvento(String nombreEvento) {
		this.nombreEvento = nombreEvento;
	}

	@Column(name = "url_redireccion", nullable = false, length = 45)
	public String geturl_redireccion() {
		return this.url_redireccion;
	}

	public void seturl_redireccion(String url_redireccion) {
		this.url_redireccion = url_redireccion;
	}


	@Column(name = "imagen_evento", nullable = false, length = 45)
	public String getImagenEvento() {
		return this.imagenEvento;
	}

	public void setImagenEvento(String imagenEvento) {
		this.imagenEvento = imagenEvento;
	}

	@Column(name = "descripcion_evento", nullable = false, length = 85)
	public String getDescripcionEvento() {
		return this.descripcionEvento;
	}

	public void setDescripcionEvento(String descripcionEvento) {
		this.descripcionEvento = descripcionEvento;
	}

}
