package entidades;
// Generated 22/11/2017 02:34:27 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * NumeroFichaEgresado generated by hbm2java
 */
@Entity
@Table(name = "numero_ficha_egresado", catalog = "egresoft")
public class NumeroFichaEgresado implements java.io.Serializable {

	private Integer idnumeroFichaEgresado;
	private Egresado egresado;
	private NumeroFicha numeroFicha;

	public NumeroFichaEgresado() {
	}

	public NumeroFichaEgresado(Egresado egresado, NumeroFicha numeroFicha) {
		this.egresado = egresado;
		this.numeroFicha = numeroFicha;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idnumero_ficha_egresado", unique = true, nullable = false)
	public Integer getIdnumeroFichaEgresado() {
		return this.idnumeroFichaEgresado;
	}

	public void setIdnumeroFichaEgresado(Integer idnumeroFichaEgresado) {
		this.idnumeroFichaEgresado = idnumeroFichaEgresado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEgresado", nullable = false)
	public Egresado getEgresado() {
		return this.egresado;
	}

	public void setEgresado(Egresado egresado) {
		this.egresado = egresado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idNumero_ficha", nullable = false)
	public NumeroFicha getNumeroFicha() {
		return this.numeroFicha;
	}

	public void setNumeroFicha(NumeroFicha numeroFicha) {
		this.numeroFicha = numeroFicha;
	}

}
