package entidades;
// Generated 22/11/2017 02:34:27 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NumeroFicha generated by hbm2java
 */
@Entity
@Table(name = "numero_ficha", catalog = "egresoft")
public class NumeroFicha implements java.io.Serializable {

	private Integer idNumeroFicha;
	private ProgramaFormacion programaFormacion;
	private String numeroDeFicha;
	private Set<NumeroFichaEgresado> numeroFichaEgresados = new HashSet<NumeroFichaEgresado>(0);

	public NumeroFicha() {
	}

	public NumeroFicha(ProgramaFormacion programaFormacion, String numeroDeFicha) {
		this.programaFormacion = programaFormacion;
		this.numeroDeFicha = numeroDeFicha;
	}

	public NumeroFicha(ProgramaFormacion programaFormacion, String numeroDeFicha,
			Set<NumeroFichaEgresado> numeroFichaEgresados) {
		this.programaFormacion = programaFormacion;
		this.numeroDeFicha = numeroDeFicha;
		this.numeroFichaEgresados = numeroFichaEgresados;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idNumero_ficha", unique = true, nullable = false)
	public Integer getIdNumeroFicha() {
		return this.idNumeroFicha;
	}

	public void setIdNumeroFicha(Integer idNumeroFicha) {
		this.idNumeroFicha = idNumeroFicha;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPrograma_formacion", nullable = false)
	public ProgramaFormacion getProgramaFormacion() {
		return this.programaFormacion;
	}

	public void setProgramaFormacion(ProgramaFormacion programaFormacion) {
		this.programaFormacion = programaFormacion;
	}

	@Column(name = "numero_de_ficha", nullable = false, length = 45)
	public String getNumeroDeFicha() {
		return this.numeroDeFicha;
	}

	public void setNumeroDeFicha(String numeroDeFicha) {
		this.numeroDeFicha = numeroDeFicha;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "numeroFicha")
	public Set<NumeroFichaEgresado> getNumeroFichaEgresados() {
		return this.numeroFichaEgresados;
	}

	public void setNumeroFichaEgresados(Set<NumeroFichaEgresado> numeroFichaEgresados) {
		this.numeroFichaEgresados = numeroFichaEgresados;
	}

}
