package entidades;
// Generated 30/10/2017 08:29:39 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * NumeroFicha generated by hbm2java
 */
@Entity
@Table(name = "numero_ficha", catalog = "egresoft")
public class NumeroFicha implements java.io.Serializable {

	private Integer idNumeroFicha;
	private Egresado egresado;
	private ProgramaFormacion programaFormacion;
	private String numeroFicha;

	public NumeroFicha() {
	}

	public NumeroFicha(Egresado egresado, ProgramaFormacion programaFormacion, String numeroFicha) {
		this.egresado = egresado;
		this.programaFormacion = programaFormacion;
		this.numeroFicha = numeroFicha;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idNumero_ficha", unique = true, nullable = false)
	public Integer getIdNumeroFicha() {
		return this.idNumeroFicha;
	}

	public void setIdNumeroFicha(Integer idNumeroFicha) {
		this.idNumeroFicha = idNumeroFicha;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEgresado", nullable = false)
	public Egresado getEgresado() {
		return this.egresado;
	}

	public void setEgresado(Egresado egresado) {
		this.egresado = egresado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idprograma_formacion", nullable = false)
	public ProgramaFormacion getProgramaFormacion() {
		return this.programaFormacion;
	}

	public void setProgramaFormacion(ProgramaFormacion programaFormacion) {
		this.programaFormacion = programaFormacion;
	}

	@Column(name = "numero_ficha", nullable = false, length = 45)
	public String getNumeroFicha() {
		return this.numeroFicha;
	}

	public void setNumeroFicha(String numeroFicha) {
		this.numeroFicha = numeroFicha;
	}

}
