package entidades;
// Generated 11/10/2017 03:41:20 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProgramaFormacion generated by hbm2java
 */
@Entity
@Table(name = "programa_formacion", catalog = "egresoft")
public class ProgramaFormacion implements java.io.Serializable {

	private Integer idProgramaFormacion;
	private String nombreFormacion;
	private int idtipoTitulacion;

	public ProgramaFormacion() {
	}

	public ProgramaFormacion(String nombreFormacion, int idtipoTitulacion) {
		this.nombreFormacion = nombreFormacion;
		this.idtipoTitulacion = idtipoTitulacion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idPrograma_formacion", unique = true, nullable = false)
	public Integer getIdProgramaFormacion() {
		return this.idProgramaFormacion;
	}

	public void setIdProgramaFormacion(Integer idProgramaFormacion) {
		this.idProgramaFormacion = idProgramaFormacion;
	}

	@Column(name = "nombre_formacion", nullable = false, length = 55)
	public String getNombreFormacion() {
		return this.nombreFormacion;
	}

	public void setNombreFormacion(String nombreFormacion) {
		this.nombreFormacion = nombreFormacion;
	}

	@Column(name = "idtipo_titulacion", nullable = false)
	public int getIdtipoTitulacion() {
		return this.idtipoTitulacion;
	}

	public void setIdtipoTitulacion(int idtipoTitulacion) {
		this.idtipoTitulacion = idtipoTitulacion;
	}

}
