package entidades;
// Generated 30/10/2017 08:29:39 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProgramaFormacion generated by hbm2java
 */
@Entity
@Table(name = "programa_formacion", catalog = "egresoft")
public class ProgramaFormacion implements java.io.Serializable {

	private Integer idProgramaFormacion;
	private TipoTitulacion tipoTitulacion;
	private String nombreFormacion;
	private Set<NumeroFicha> numeroFichas = new HashSet<NumeroFicha>(0);

	public ProgramaFormacion() {
	}

	public ProgramaFormacion(TipoTitulacion tipoTitulacion, String nombreFormacion) {
		this.tipoTitulacion = tipoTitulacion;
		this.nombreFormacion = nombreFormacion;
	}

	public ProgramaFormacion(TipoTitulacion tipoTitulacion, String nombreFormacion, Set<NumeroFicha> numeroFichas) {
		this.tipoTitulacion = tipoTitulacion;
		this.nombreFormacion = nombreFormacion;
		this.numeroFichas = numeroFichas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idPrograma_formacion", unique = true, nullable = false)
	public Integer getIdProgramaFormacion() {
		return this.idProgramaFormacion;
	}

	public void setIdProgramaFormacion(Integer idProgramaFormacion) {
		this.idProgramaFormacion = idProgramaFormacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipo_titulacion", nullable = false)
	public TipoTitulacion getTipoTitulacion() {
		return this.tipoTitulacion;
	}

	public void setTipoTitulacion(TipoTitulacion tipoTitulacion) {
		this.tipoTitulacion = tipoTitulacion;
	}

	@Column(name = "nombre_formacion", nullable = false, length = 55)
	public String getNombreFormacion() {
		return this.nombreFormacion;
	}

	public void setNombreFormacion(String nombreFormacion) {
		this.nombreFormacion = nombreFormacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "programaFormacion")
	public Set<NumeroFicha> getNumeroFichas() {
		return this.numeroFichas;
	}

	public void setNumeroFichas(Set<NumeroFicha> numeroFichas) {
		this.numeroFichas = numeroFichas;
	}

}
