package entidades;
// Generated 11/10/2017 03:41:20 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoTitulacion generated by hbm2java
 */
@Entity
@Table(name = "tipo_titulacion", catalog = "egresoft")
public class TipoTitulacion implements java.io.Serializable {

	private Integer idTipoTitulacion;
	private String tipoTitulacion;

	public TipoTitulacion() {
	}

	public TipoTitulacion(String tipoTitulacion) {
		this.tipoTitulacion = tipoTitulacion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idTipo_titulacion", unique = true, nullable = false)
	public Integer getIdTipoTitulacion() {
		return this.idTipoTitulacion;
	}

	public void setIdTipoTitulacion(Integer idTipoTitulacion) {
		this.idTipoTitulacion = idTipoTitulacion;
	}

	@Column(name = "tipo_titulacion", nullable = false, length = 45)
	public String getTipoTitulacion() {
		return this.tipoTitulacion;
	}

	public void setTipoTitulacion(String tipoTitulacion) {
		this.tipoTitulacion = tipoTitulacion;
	}

}
