package entidades;
// Generated 22/11/2017 02:34:27 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TipoTitulacion generated by hbm2java
 */
@Entity
@Table(name = "tipo_titulacion", catalog = "egresoft", uniqueConstraints = @UniqueConstraint(columnNames = "tipo_titulacion"))
public class TipoTitulacion implements java.io.Serializable {

	private Integer idTipoTitulacion;
	private String tipoTitulacion;
	private Set<ProgramaFormacion> programaFormacions = new HashSet<ProgramaFormacion>(0);

	public TipoTitulacion() {
	}

	public TipoTitulacion(String tipoTitulacion) {
		this.tipoTitulacion = tipoTitulacion;
	}

	public TipoTitulacion(String tipoTitulacion, Set<ProgramaFormacion> programaFormacions) {
		this.tipoTitulacion = tipoTitulacion;
		this.programaFormacions = programaFormacions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idTipo_titulacion", unique = true, nullable = false)
	public Integer getIdTipoTitulacion() {
		return this.idTipoTitulacion;
	}

	public void setIdTipoTitulacion(Integer idTipoTitulacion) {
		this.idTipoTitulacion = idTipoTitulacion;
	}

	@Column(name = "tipo_titulacion", unique = true, nullable = false, length = 45)
	public String getTipoTitulacion() {
		return this.tipoTitulacion;
	}

	public void setTipoTitulacion(String tipoTitulacion) {
		this.tipoTitulacion = tipoTitulacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoTitulacion")
	public Set<ProgramaFormacion> getProgramaFormacions() {
		return this.programaFormacions;
	}

	public void setProgramaFormacions(Set<ProgramaFormacion> programaFormacions) {
		this.programaFormacions = programaFormacions;
	}

}
