package entidades;
// Generated 22/11/2017 02:34:27 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Vistaegresado generated by hbm2java
 */
@Entity
@Table(name = "vistaegresado", catalog = "egresoft")
public class Vistaegresado implements java.io.Serializable {

	private VistaegresadoId id;

	public Vistaegresado() {
	}

	public Vistaegresado(VistaegresadoId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idEgresado", column = @Column(name = "idEgresado", nullable = false)),
			@AttributeOverride(name = "tipoDocumento", column = @Column(name = "tipo_documento", nullable = false, length = 45)),
			@AttributeOverride(name = "nombres", column = @Column(name = "nombres", nullable = false, length = 45)),
			@AttributeOverride(name = "apellidos", column = @Column(name = "apellidos", nullable = false, length = 45)),
			@AttributeOverride(name = "telefonoPrincipal", column = @Column(name = "telefono_principal", length = 45)),
			@AttributeOverride(name = "telefonoAlterno", column = @Column(name = "telefono_alterno", length = 45)),
			@AttributeOverride(name = "emailPrincipal", column = @Column(name = "email_principal", nullable = false, length = 45)),
			@AttributeOverride(name = "emailAlterno", column = @Column(name = "email_alterno", length = 45)),
			@AttributeOverride(name = "lugarResidencia", column = @Column(name = "lugar_residencia", length = 45)),
			@AttributeOverride(name = "contrasena", column = @Column(name = "contrasena", length = 45)),
			@AttributeOverride(name = "modalidad", column = @Column(name = "modalidad", length = 45)),
			@AttributeOverride(name = "fechaInicio", column = @Column(name = "fecha_inicio", length = 10)),
			@AttributeOverride(name = "fechaFin", column = @Column(name = "fecha_fin", length = 10)),
			@AttributeOverride(name = "numeroDeFicha", column = @Column(name = "numero_de_ficha", nullable = false, length = 45)),
			@AttributeOverride(name = "nombreFormacion", column = @Column(name = "nombre_formacion", nullable = false, length = 55)),
			@AttributeOverride(name = "tipoTitulacion", column = @Column(name = "tipo_titulacion", nullable = false, length = 45)) })
	public VistaegresadoId getId() {
		return this.id;
	}

	public void setId(VistaegresadoId id) {
		this.id = id;
	}

}
