package entidades;
// Generated 3/12/2017 09:41:36 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VistaegresadosId generated by hbm2java
 */
@Embeddable
public class VistaegresadosId implements java.io.Serializable {

	private long idEgresado;
	private String tipoDocumento;
	private String nombres;
	private String apellidos;
	private String telefonoPrincipal;
	private String telefonoAlterno;
	private String emailPrincipal;
	private String emailAlterno;
	private String lugarResidencia;
	private String contrasena;
	private String modalidad;
	private Date fechaInicio;
	private Date fechaFin;
	private String numeroDeFicha;
	private String nombreFormacion;
	private String tipoTitulacion;

	public VistaegresadosId() {
	}

	public VistaegresadosId(long idEgresado, String tipoDocumento, String nombres, String apellidos,
			String emailPrincipal, String numeroDeFicha, String nombreFormacion, String tipoTitulacion) {
		this.idEgresado = idEgresado;
		this.tipoDocumento = tipoDocumento;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.emailPrincipal = emailPrincipal;
		this.numeroDeFicha = numeroDeFicha;
		this.nombreFormacion = nombreFormacion;
		this.tipoTitulacion = tipoTitulacion;
	}

	public VistaegresadosId(long idEgresado, String tipoDocumento, String nombres, String apellidos,
			String telefonoPrincipal, String telefonoAlterno, String emailPrincipal, String emailAlterno,
			String lugarResidencia, String contrasena, String modalidad, Date fechaInicio, Date fechaFin,
			String numeroDeFicha, String nombreFormacion, String tipoTitulacion) {
		this.idEgresado = idEgresado;
		this.tipoDocumento = tipoDocumento;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.telefonoPrincipal = telefonoPrincipal;
		this.telefonoAlterno = telefonoAlterno;
		this.emailPrincipal = emailPrincipal;
		this.emailAlterno = emailAlterno;
		this.lugarResidencia = lugarResidencia;
		this.contrasena = contrasena;
		this.modalidad = modalidad;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.numeroDeFicha = numeroDeFicha;
		this.nombreFormacion = nombreFormacion;
		this.tipoTitulacion = tipoTitulacion;
	}

	@Column(name = "idEgresado", nullable = false)
	public long getIdEgresado() {
		return this.idEgresado;
	}

	public void setIdEgresado(long idEgresado) {
		this.idEgresado = idEgresado;
	}

	@Column(name = "tipo_documento", nullable = false, length = 45)
	public String getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	@Column(name = "nombres", nullable = false, length = 45)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "apellidos", nullable = false, length = 45)
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Column(name = "telefono_principal", length = 45)
	public String getTelefonoPrincipal() {
		return this.telefonoPrincipal;
	}

	public void setTelefonoPrincipal(String telefonoPrincipal) {
		this.telefonoPrincipal = telefonoPrincipal;
	}

	@Column(name = "telefono_alterno", length = 45)
	public String getTelefonoAlterno() {
		return this.telefonoAlterno;
	}

	public void setTelefonoAlterno(String telefonoAlterno) {
		this.telefonoAlterno = telefonoAlterno;
	}

	@Column(name = "email_principal", nullable = false, length = 45)
	public String getEmailPrincipal() {
		return this.emailPrincipal;
	}

	public void setEmailPrincipal(String emailPrincipal) {
		this.emailPrincipal = emailPrincipal;
	}

	@Column(name = "email_alterno", length = 45)
	public String getEmailAlterno() {
		return this.emailAlterno;
	}

	public void setEmailAlterno(String emailAlterno) {
		this.emailAlterno = emailAlterno;
	}

	@Column(name = "lugar_residencia", length = 45)
	public String getLugarResidencia() {
		return this.lugarResidencia;
	}

	public void setLugarResidencia(String lugarResidencia) {
		this.lugarResidencia = lugarResidencia;
	}

	@Column(name = "contrasena", length = 45)
	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	@Column(name = "modalidad", length = 45)
	public String getModalidad() {
		return this.modalidad;
	}

	public void setModalidad(String modalidad) {
		this.modalidad = modalidad;
	}

	@Column(name = "fecha_inicio", length = 10)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Column(name = "fecha_fin", length = 10)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "numero_de_ficha", nullable = false, length = 45)
	public String getNumeroDeFicha() {
		return this.numeroDeFicha;
	}

	public void setNumeroDeFicha(String numeroDeFicha) {
		this.numeroDeFicha = numeroDeFicha;
	}

	@Column(name = "nombre_formacion", nullable = false, length = 105)
	public String getNombreFormacion() {
		return this.nombreFormacion;
	}

	public void setNombreFormacion(String nombreFormacion) {
		this.nombreFormacion = nombreFormacion;
	}

	@Column(name = "tipo_titulacion", nullable = false, length = 45)
	public String getTipoTitulacion() {
		return this.tipoTitulacion;
	}

	public void setTipoTitulacion(String tipoTitulacion) {
		this.tipoTitulacion = tipoTitulacion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VistaegresadosId))
			return false;
		VistaegresadosId castOther = (VistaegresadosId) other;

		return (this.getIdEgresado() == castOther.getIdEgresado())
				&& ((this.getTipoDocumento() == castOther.getTipoDocumento())
						|| (this.getTipoDocumento() != null && castOther.getTipoDocumento() != null
								&& this.getTipoDocumento().equals(castOther.getTipoDocumento())))
				&& ((this.getNombres() == castOther.getNombres()) || (this.getNombres() != null
						&& castOther.getNombres() != null && this.getNombres().equals(castOther.getNombres())))
				&& ((this.getApellidos() == castOther.getApellidos()) || (this.getApellidos() != null
						&& castOther.getApellidos() != null && this.getApellidos().equals(castOther.getApellidos())))
				&& ((this.getTelefonoPrincipal() == castOther.getTelefonoPrincipal())
						|| (this.getTelefonoPrincipal() != null && castOther.getTelefonoPrincipal() != null
								&& this.getTelefonoPrincipal().equals(castOther.getTelefonoPrincipal())))
				&& ((this.getTelefonoAlterno() == castOther.getTelefonoAlterno())
						|| (this.getTelefonoAlterno() != null && castOther.getTelefonoAlterno() != null
								&& this.getTelefonoAlterno().equals(castOther.getTelefonoAlterno())))
				&& ((this.getEmailPrincipal() == castOther.getEmailPrincipal())
						|| (this.getEmailPrincipal() != null && castOther.getEmailPrincipal() != null
								&& this.getEmailPrincipal().equals(castOther.getEmailPrincipal())))
				&& ((this.getEmailAlterno() == castOther.getEmailAlterno())
						|| (this.getEmailAlterno() != null && castOther.getEmailAlterno() != null
								&& this.getEmailAlterno().equals(castOther.getEmailAlterno())))
				&& ((this.getLugarResidencia() == castOther.getLugarResidencia())
						|| (this.getLugarResidencia() != null && castOther.getLugarResidencia() != null
								&& this.getLugarResidencia().equals(castOther.getLugarResidencia())))
				&& ((this.getContrasena() == castOther.getContrasena()) || (this.getContrasena() != null
						&& castOther.getContrasena() != null && this.getContrasena().equals(castOther.getContrasena())))
				&& ((this.getModalidad() == castOther.getModalidad()) || (this.getModalidad() != null
						&& castOther.getModalidad() != null && this.getModalidad().equals(castOther.getModalidad())))
				&& ((this.getFechaInicio() == castOther.getFechaInicio())
						|| (this.getFechaInicio() != null && castOther.getFechaInicio() != null
								&& this.getFechaInicio().equals(castOther.getFechaInicio())))
				&& ((this.getFechaFin() == castOther.getFechaFin()) || (this.getFechaFin() != null
						&& castOther.getFechaFin() != null && this.getFechaFin().equals(castOther.getFechaFin())))
				&& ((this.getNumeroDeFicha() == castOther.getNumeroDeFicha())
						|| (this.getNumeroDeFicha() != null && castOther.getNumeroDeFicha() != null
								&& this.getNumeroDeFicha().equals(castOther.getNumeroDeFicha())))
				&& ((this.getNombreFormacion() == castOther.getNombreFormacion())
						|| (this.getNombreFormacion() != null && castOther.getNombreFormacion() != null
								&& this.getNombreFormacion().equals(castOther.getNombreFormacion())))
				&& ((this.getTipoTitulacion() == castOther.getTipoTitulacion())
						|| (this.getTipoTitulacion() != null && castOther.getTipoTitulacion() != null
								&& this.getTipoTitulacion().equals(castOther.getTipoTitulacion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdEgresado();
		result = 37 * result + (getTipoDocumento() == null ? 0 : this.getTipoDocumento().hashCode());
		result = 37 * result + (getNombres() == null ? 0 : this.getNombres().hashCode());
		result = 37 * result + (getApellidos() == null ? 0 : this.getApellidos().hashCode());
		result = 37 * result + (getTelefonoPrincipal() == null ? 0 : this.getTelefonoPrincipal().hashCode());
		result = 37 * result + (getTelefonoAlterno() == null ? 0 : this.getTelefonoAlterno().hashCode());
		result = 37 * result + (getEmailPrincipal() == null ? 0 : this.getEmailPrincipal().hashCode());
		result = 37 * result + (getEmailAlterno() == null ? 0 : this.getEmailAlterno().hashCode());
		result = 37 * result + (getLugarResidencia() == null ? 0 : this.getLugarResidencia().hashCode());
		result = 37 * result + (getContrasena() == null ? 0 : this.getContrasena().hashCode());
		result = 37 * result + (getModalidad() == null ? 0 : this.getModalidad().hashCode());
		result = 37 * result + (getFechaInicio() == null ? 0 : this.getFechaInicio().hashCode());
		result = 37 * result + (getFechaFin() == null ? 0 : this.getFechaFin().hashCode());
		result = 37 * result + (getNumeroDeFicha() == null ? 0 : this.getNumeroDeFicha().hashCode());
		result = 37 * result + (getNombreFormacion() == null ? 0 : this.getNombreFormacion().hashCode());
		result = 37 * result + (getTipoTitulacion() == null ? 0 : this.getTipoTitulacion().hashCode());
		return result;
	}

}
